### ISSUE TITLE
composer 失败

### ISSUE THREAD

**Issue by day112** [valiner/identicon-avatar#2]
![image](https://user-images.githubusercontent.com/10526728/66975698-d9895d00-f0d1-11e9-8303-19ec1ee0cb1f.png)
![image](https://user-images.githubusercontent.com/10526728/66975718-ead26980-f0d1-11e9-9cf3-4e791ddc8288.png)

**Comment by ygcool** [comment]
我也遇到同样问题，在laravel默认有phpunit，此项目又必须依赖phpunit，导致这个报错， 请问你解决了吗？

**Comment by inbjo** [comment]
项目依赖的phpunit版本太低，和新版本的laravel依赖的phpunit版本冲突了
